---
- hosts: "localhost"
  vars_files:
  - vars.yml

  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response
    
  - name: "delete-host-sequence"
    check_point_mgmt:
      command: delete-host
      parameters:
        name: "cpx-host{{item}}"
      session-data: "{{login_response}}"
    with_sequence: start=1 end=25

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "logout"
    check_point_mgmt:
      command: logout 
      session-data: "{{login_response}}"
